# Generated by Django 5.2.10 on 2026-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_password_hash_user_password_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_disease',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_tone',
            field=models.CharField(blank=True, choices=[('fair', 'Fair'), ('medium', 'Medium'), ('dark', 'Dark')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('oily', 'Oily'), ('combination', 'Combination'), ('dry', 'Dry')], default='', max_length=20),
        ),
    ]
