# Generated by Django 6.1.1 on 2026-09-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='age_bracket',
            field=models.CharField(blank=True, choices=[('teen', 'Teen'), ('18-24', '18-24'), ('25-34', '25-34'), ('35+', '35+')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='current_products',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pregnant_or_breastfeeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('oily', 'Oily'), ('combination', 'Combination'), ('dry', 'Dry'), ('normal', 'Normal')], default='', max_length=20),
        ),
    ]
