# Generated by Django 6.1.1 on 2026-09-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_user_date_of_birth_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, default='', max_length=20)),
                ('skin_type_confidence', models.FloatField(blank=True, null=True)),
                ('skin_tone', models.CharField(blank=True, default='', max_length=20)),
                ('skin_tone_confidence', models.FloatField(blank=True, null=True)),
                ('skin_disease', models.CharField(blank=True, default='', max_length=255)),
                ('skin_disease_confidence', models.FloatField(blank=True, null=True)),
                ('disease_detected', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('full_scan', 'Full scan (all 3 models)'), ('manual', 'Manual entry')], default='full_scan', max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_scans', to='Users.user')),
            ],
            options={
                'db_table': 'skin_scan_history',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
