# Generated by Django 6.1.1 on 2026-09-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_skinscanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinscanhistory',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.AddField(
            model_name='skinscanhistory',
            name='image_processed',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
    ]
